### PR TITLE
First Stable Implementation of A2HS

### LINKED ISSUE #21: Enable A2HS for mobile

### PR DESCRIPTION
**Pull request by TheNickRyan**
### A2HS 1.0 ###

Spicebutton now registers a [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) when a user clicks the Launch POS button, allowing for [A2HS](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen) functionality to appear in the browser. Any future visit to the page will load cache data before network calls and will continue to show A2HS browser functionality.

A2HS works on both **desktop** and **mobile**.

Other major edits have been made, namely:
- Project file structure reorganized
- `utils.js` renamed to `main.js`, **lots of different edits in this file**
- 192px and 512px icons added
- `spicebutton.webmanifest` and `serviceworker.js` added for A2HS
- `slpAddress` text input now checks for matching pattern before displaying currencies in a dropdown for user selection
- Currencies loaded from [CoinGecko API](https://www.coingecko.com/en/api)
- `address` and `currency` are stored in `localStorage` for continuous access
- Back button added to keypad to allow user changes to SLP address and/or currency unit or to view widget content (which I believe is somewhat deprecated)
- Proper currency symbols added to most currencies that have UTF-8 symbols (some read RTL based on country)
- **Minified files were removed during this process**. They have been recreated for all vital files and stored in `spicebutton/min`.

This is only the first implementation, I expect more changes to come in the future regarding caching and networking calls using [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

### CODE REVIEW

**Comment by JettScythe** [comment]
https://bchpizza.org/ does use the minified scripts, so we need to restore them before merging.

**Comment by TheNickRyan** [comment]
> https://bchpizza.org/ does use the minified scripts, so we need to restore them before merging.

@JettScythe Turns out, they don't use the minified scripts, as I just went through the entire page. They do, however, use spicebutton.js as well as buttons.css, modal.css and qrjs2.js, and they pull them directly from the master server at https://spicebutton.com/pre-release/v0.1/"folder"/"filename". We'll just need them to change the call they make to https://spicebutton.com/"folder"/"filename" and it should still work as per usual.

**Comment by JettScythe** [comment]
Marked as draft until we get the minified stuff finished as well as documentation updated.

**Comment by TheNickRyan** [comment]
Made a new commit to add minified files back to the project under `spicebutton/min`.

With this commit I also replaced the hardcoded .svg sources in the `index.html` with `spice_master_trans_bg_black_outer_no_text.svg`, and ended up saving 290Kb of data.

Everything should be clear now. For anyone using minified files in the future, they will be in the `/min` directory, and we can start pointing to them.

**Comment by alt-win** [comment]
I'm really pleased with the changes to the UI, and how much the code has been simplified.  Props to @TheNickRyan and @JettScythe for this pull.  Cheers.

**Pull request merged**
